"""Document model."""

from ezf3d.model.design import Component, Design, read_design
from ezf3d.model.document import (
    DESIGN_SUFFIX,
    PACKAGE_SUFFIX,
    Asset,
    Body,
    Document,
    Ef3dError,
    readfile,
)
from ezf3d.model.materials import Assignment, Materials, read_assignments, read_catalogue
from ezf3d.model.parameters import Parameter, Parameters, read_parameters
from ezf3d.model.placement import (
    Frame,
    Placement,
    Placements,
    SketchEdge,
    closure_check,
    place_by_edges,
    place_sketches,
    sketch_edges,
)
from ezf3d.model.sketch import (
    Curve,
    Loop,
    Point,
    Sketch,
    Sketches,
    read_curve,
    read_sketches,
)
from ezf3d.model.timeline import Extrude, Feature, Timeline, read_extrude, read_timeline

__all__ = [
    "DESIGN_SUFFIX",
    "PACKAGE_SUFFIX",
    "Asset",
    "Assignment",
    "Body",
    "Component",
    "Curve",
    "Design",
    "Document",
    "Ef3dError",
    "Extrude",
    "Feature",
    "Frame",
    "Loop",
    "Materials",
    "Parameter",
    "Parameters",
    "Placement",
    "Placements",
    "Point",
    "Sketch",
    "SketchEdge",
    "Sketches",
    "Timeline",
    "closure_check",
    "place_by_edges",
    "place_sketches",
    "read_assignments",
    "read_catalogue",
    "read_curve",
    "read_design",
    "read_extrude",
    "read_parameters",
    "read_sketches",
    "read_timeline",
    "readfile",
    "sketch_edges",
]

from ezf3d.model.report import (
    AssetInfo,
    BodyInfo,
    BoundsInfo,
    DocumentInfo,
    Envelope,
    KernelInfo,
    PackageInfo,
    PackageMember,
    ParameterInfo,
    ParametersInfo,
    PlacementInfo,
    SegmentInfo,
    SketchesInfo,
    SketchInfo,
    TimelineEntry,
    TimelineInfo,
    Totals,
)

__all__ += [
    "AssetInfo",
    "BodyInfo",
    "BoundsInfo",
    "DocumentInfo",
    "Envelope",
    "KernelInfo",
    "PackageInfo",
    "PackageMember",
    "ParameterInfo",
    "ParametersInfo",
    "PlacementInfo",
    "SegmentInfo",
    "SketchInfo",
    "SketchesInfo",
    "TimelineEntry",
    "TimelineInfo",
    "Totals",
]
